services:
  nextjs-app:
    container_name: nextjs-app
    image: node:22-alpine
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules  # Prevents overwriting node_modules from host
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
